apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager-webhook-hosttech.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cert-manager-webhook-hosttech.name" . }}
    chart: {{ include "cert-manager-webhook-hosttech.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: https-cert-manager-webhook-hosttech
  selector:
    app: {{ include "cert-manager-webhook-hosttech.name" . }}
    release: {{ .Release.Name }}
