---
name: Docker Image CI Build

on:
  push:
    branches:
      - main

jobs:
  docker:
    if: ${{ (contains(github.event.head_commit.message, '[PRERELEASE]')) || ((contains(github.event.head_commit.message, '[RELEASE]'))) }}
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Create automagically a new semantic version
        uses: paulhatch/semantic-version@v5.0.0-beta2
        id: semantic_version
        with:
          tag_prefix: "v"
          major_pattern: "[MAJOR]"
          minor_pattern: "[MINOR]"
          version_format: "${major}.${minor}.${patch}-rc${increment}"
      -
        name: Create tag
        if: (contains(github.event.head_commit.message, '[MAJOR]')) || (contains(github.event.head_commit.message, '[MINOR]'))
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.semantic_version.outputs.version }}
      -
        name: Build and push prerelease
        if: (contains(github.event.head_commit.message, '[MAJOR]')) || (contains(github.event.head_commit.message, '[MINOR]'))
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: piccobit/cert-manager-webhook-hosttech:${{ steps.semantic_version.outputs.version }}
