---
name: Docker Image CI Build

on:
  push:
    branches:
      - main

jobs:
  docker:
    if: contains(github.event.head_commit.message, '[RELEASE]') || contains(github.event.head_commit.message, '[PRERELEASE]') || contains(github.event.head_commit.message, '[DEBUG]')
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Calculate new semantic debug version
        if: contains(github.event.head_commit.message, '[DEBUG]')
        uses: zwaldowski/semver-release-action@v3
        id: semantic_version_debug
        with:
          bump: preminor
          preid: dbg
          github_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Calculate new semantic pre-release version
        if: contains(github.event.head_commit.message, '[PRERELEASE]')
        uses: zwaldowski/semver-release-action@v3
        id: semantic_version_prelease
        with:
          bump: preminor
          preid: rc
          github_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Calculate new semantic release version
        if: contains(github.event.head_commit.message, '[RELEASE]')
        uses: zwaldowski/semver-release-action@v3
        id: semantic_version_release
        with:
          bump: minor
          github_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push debug release
        if: contains(github.event.head_commit.message, '[DEBUG]')
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.debug
          platforms: linux/amd64
          push: true
          tags: piccobit/cert-manager-webhook-hosttech:${{ steps.semantic_version_debug.outputs.version }}
      -
        name: Build and push pre-release
        if: contains(github.event.head_commit.message, '[PRERELEASE]')
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: piccobit/cert-manager-webhook-hosttech:${{ steps.semantic_version_prerelease.outputs.version }}
      -
        name: Build and push release
        if: contains(github.event.head_commit.message, '[RELEASE]')
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: piccobit/cert-manager-webhook-hosttech:${{ steps.semantic_version_release.outputs.version }}
