---
name: Docker Image CI Build

on:
  push:
    branches:
      - main

jobs:
  docker:
    if: contains(github.event.head_commit.message, '[RELEASE]') || contains(github.event.head_commit.message, '[PRERELEASE]') || contains(github.event.head_commit.message, '[DEBUG]')
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Create automagically a new semantic version for every commit which is not either a debug, pre or normal release
        if: !contains(github.event.head_commit.message, '[DEBUG]') && !contains(github.event.head_commit.message, '[PRERELEASE]') && !contains(github.event.head_commit.message, '[RELEASE]')
        uses: paulhatch/semantic-version@v5.0.0-beta2
        id: semantic_version_release
        with:
          tag_prefix: "v"
          major_pattern: "[MAJOR]"
          minor_pattern: "[MINOR]"
          version_format: "${major}.${minor}.${patch}+${increment}"
      -
        name: Create automagically a new semantic version for the releases
        if: contains(github.event.head_commit.message, '[RELEASE]')
        uses: paulhatch/semantic-version@v5.0.0-beta2
        id: semantic_version_release
        with:
          tag_prefix: "v"
          major_pattern: "[MAJOR]"
          minor_pattern: "[MINOR]"
          version_format: "${major}.${minor}.${patch}"
      -
        name: Create automagically a new semantic version for the pre-releases
        if: contains(github.event.head_commit.message, '[PRERELEASE]')
        uses: paulhatch/semantic-version@v5.0.0-beta2
        id: semantic_version_prerelease
        with:
          tag_prefix: "v"
          major_pattern: "[MAJOR]"
          minor_pattern: "[MINOR]"
          version_format: "${major}.${minor}.${patch}-rc${increment}"
      -
        name: Create automagically a new semantic version for the debug pre-releases
        if: contains(github.event.head_commit.message, '[DEBUG]')
        uses: paulhatch/semantic-version@v5.0.0-beta2
        id: semantic_version_debug
        with:
          tag_prefix: "v"
          major_pattern: "[MAJOR]"
          minor_pattern: "[MINOR]"
          version_format: "${major}.${minor}.${patch}-dbg${increment}"
      -
        name: Create tag for every new commit which is not either a debug, pre or normal release
        if: !contains(github.event.head_commit.message, '[DEBUG]') && !contains(github.event.head_commit.message, '[PRERELEASE]') && !contains(github.event.head_commit.message, '[RELEASE]')
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.semantic_version_debug.outputs.version }}
      -
        name: Create tag for debug pre-releases
        if: contains(github.event.head_commit.message, '[DEBUG]')
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.semantic_version_debug.outputs.version }}
      -
        name: Create tag for pre-releases
        if: contains(github.event.head_commit.message, '[PRERELEASE]')
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.semantic_version_prerelease.outputs.version }}
      -
        name: Create tag for releases
        if: contains(github.event.head_commit.message, '[RELEASE]')
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.semantic_version_release.outputs.version }}
      -
        name: Build and push debug release
        if: contains(github.event.head_commit.message, '[DEBUG]')
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.debug
          platforms: linux/amd64
          push: true
          tags: piccobit/cert-manager-webhook-hosttech:${{ steps.semantic_version_debug.outputs.version }}
      -
        name: Build and push pre-release
        if: contains(github.event.head_commit.message, '[PRERELEASE]')
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: piccobit/cert-manager-webhook-hosttech:${{ steps.semantic_version_prerelease.outputs.version }}
      -
        name: Build and push release
        if: contains(github.event.head_commit.message, '[RELEASE]')
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: piccobit/cert-manager-webhook-hosttech:${{ steps.semantic_version_release.outputs.version }}
