---
name: Docker Image CI - Release Build

on:
  push:
    branches:
      - main

jobs:
  semantic_version:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Create automagically a new semantic version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          major_pattern: "[MAJOR]"
          minor_pattern: "[MINOR]"
          format: "${major}.${minor}.${patch}-rc${increment}"

  docker:
    needs: semantic_version
    if: ${{ (contains(github.event.head_commit.message, '[MAJOR]')) || ((contains(github.event.head_commit.message, '[MINOR]'))) }}
    runs-on: ubuntu-22.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: piccobit/cert-manager-webhook-hosttech:${{ github.ref_name }}
