---
name: Docker Image CI Build

on:
  push:
    branches:
      - main

jobs:
  docker:
    if: contains(github.event.head_commit.message, '[RELEASE]') || contains(github.event.head_commit.message, '[PRERELEASE]') || contains(github.event.head_commit.message, '[DEBUG]')
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Calculate new semantic pre-patch version
        if: contains(github.event.head_commit.message, '[PREPATCH]')
        uses: zwaldowski/semver-release-action@v3
        id: semantic_version_pre_patch
        with:
          bump: prepatch
          github_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Calculate new semantic patch version
        if: contains(github.event.head_commit.message, '[PATCH]')
        uses: zwaldowski/semver-release-action@v3
        id: semantic_version_patch
        with:
          bump: patch
          github_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Calculate new semantic pre-minor version
        if: contains(github.event.head_commit.message, '[PREMINOR]')
        uses: zwaldowski/semver-release-action@v3
        id: semantic_version_pre_minor
        with:
          bump: preminor
          github_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Calculate new semantic minor version
        if: contains(github.event.head_commit.message, '[MINOR]')
        uses: zwaldowski/semver-release-action@v3
        id: semantic_version_minor
        with:
          bump: minor
          github_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Calculate new semantic pre-major version
        if: contains(github.event.head_commit.message, '[PREMAJOR]')
        uses: zwaldowski/semver-release-action@v3
        id: semantic_version_pre_major
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Calculate new semantic major version
        if: contains(github.event.head_commit.message, '[MAJOR]')
        uses: zwaldowski/semver-release-action@v3
        id: semantic_version_major
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push debug release
        if: contains(github.event.head_commit.message, '[DEBUG]')
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.debug
          platforms: linux/amd64
          push: true
          tags: piccobit/cert-manager-webhook-hosttech:${{ github.ref_name }}-dbg
      -
        name: Build and push pre-release
        if: contains(github.event.head_commit.message, '[PRERELEASE]')
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: piccobit/cert-manager-webhook-hosttech:${{ github.ref_name }}-rc
      -
        name: Build and push release
        if: contains(github.event.head_commit.message, '[RELEASE]')
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: piccobit/cert-manager-webhook-hosttech:${{ github.ref_name }}
